//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MV_P1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Libro
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Libro()
        {
            this.Prestamos_Libros = new HashSet<Prestamos_Libros>();
            this.Venta_Libros = new HashSet<Venta_Libros>();
        }
    
        public int id_Libro { get; set; }
        public string Nombre { get; set; }
        public string Editorial { get; set; }
        public string Autor { get; set; }
        public string Genero { get; set; }
        public string PaisOrigen { get; set; }
        public Nullable<int> NoPaginas { get; set; }
        public Nullable<System.DateTime> FechaEdicion { get; set; }
        public Nullable<double> Precio { get; set; }
        public Nullable<int> id_TipoLibro { get; set; }
    
        public virtual Tipos_Libros Tipos_Libros { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Prestamos_Libros> Prestamos_Libros { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Venta_Libros> Venta_Libros { get; set; }
    }
}
