//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MV_P1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Prestamos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_Prestamos()
        {
            this.tbl_Prestamos_Libros = new HashSet<tbl_Prestamos_Libros>();
        }
    
        public int id_Prestamo { get; set; }
        public Nullable<System.DateTime> Fecha_de_Salida { get; set; }
        public Nullable<System.DateTime> Fecha_maxima_de_devolucion { get; set; }
        public Nullable<System.DateTime> Fecha_de_devolucion { get; set; }
        public Nullable<int> id_Usuarios { get; set; }
        public Nullable<int> id_Tipos_de_prestamos { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Prestamos_Libros> tbl_Prestamos_Libros { get; set; }
        public virtual tbl_Tipos_de_prestamos tbl_Tipos_de_prestamos { get; set; }
        public virtual tbl_Usuarios tbl_Usuarios { get; set; }
    }
}
