//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MV_P1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Libros
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_Libros()
        {
            this.tbl_Prestamos_Libros = new HashSet<tbl_Prestamos_Libros>();
            this.tbl_Venta_Libros = new HashSet<tbl_Venta_Libros>();
        }
    
        public int id_Libro { get; set; }
        public string Nombre { get; set; }
        public string Editorial { get; set; }
        public string Autor { get; set; }
        public string Genero { get; set; }
        public string PaisOrigen { get; set; }
        public Nullable<int> NoPaginas { get; set; }
        public Nullable<System.DateTime> FechaEdicion { get; set; }
        public Nullable<double> Precio { get; set; }
        public Nullable<int> id_TipoLibro { get; set; }
    
        public virtual tbl_Tipos_Libros tbl_Tipos_Libros { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Prestamos_Libros> tbl_Prestamos_Libros { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Venta_Libros> tbl_Venta_Libros { get; set; }
    }
}
