//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MV_P1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Venta
    {
        public int id_Venta { get; set; }
        public Nullable<double> Total { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public Nullable<System.TimeSpan> Hora { get; set; }
        public Nullable<int> id_Empleados { get; set; }
        public Nullable<int> id_Venta_Libros { get; set; }
    
        public virtual Empleado Empleado { get; set; }
        public virtual Venta_Libros Venta_Libros { get; set; }
    }
}
